-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 15:03:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acaiteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acaiteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acaiteria` DEFAULT CHARACTER SET utf8mb4 ;
USE `acaiteria` ;

-- -----------------------------------------------------
-- Table `acaiteria`.`localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acaiteria`.`localidade` (
  `idLocalidade` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `permissao` VARCHAR(45) NULL COMMENT '0 - Permitido\n1 - Não permitido',
  PRIMARY KEY (`idLocalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acaiteria`.`franquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acaiteria`.`franquia` (
  `idFranquia` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `qtde_atual` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `localidade_idLocalidade` INT NOT NULL,
  PRIMARY KEY (`idFranquia`, `localidade_idLocalidade`),
  INDEX `fk_franquia_localidade1_idx` (`localidade_idLocalidade` ASC),
  CONSTRAINT `fk_franquia_localidade1`
    FOREIGN KEY (`localidade_idLocalidade`)
    REFERENCES `acaiteria`.`localidade` (`idLocalidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acaiteria`.`franqueado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acaiteria`.`franqueado` (
  `idFranqueado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fone` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `franquia_idFranquia` INT NOT NULL,
  PRIMARY KEY (`idFranqueado`, `franquia_idFranquia`),
  INDEX `fk_franqueado_franquia_idx` (`franquia_idFranquia` ASC),
  CONSTRAINT `fk_franqueado_franquia`
    FOREIGN KEY (`franquia_idFranquia`)
    REFERENCES `acaiteria`.`franquia` (`idFranquia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
